[package]
name = "etherparse"
version = "0.4.0"
authors = ["Julian Schmid <info@julianschmid.name>"]
repository = "https://github.com/JulianSchmid/etherparse"
description = "A library for parsing & writing a bunch of packet based protocols (EthernetII, IPv4, IPv6, UDP ...)."
keywords = ["ethernet", "ipv4", "ipv6", "vlan", "udp"]
license = "BSD-3-Clause"
readme = "README.md"
exclude = [
    ".gitignore",
    ".travis.yml",
]

[dependencies]
byteorder = "1.2.1"
proptest = { version = "0.7.1", optional = true }

[dev-dependencies]
assert_matches = "1.2"
proptest = "0.7.1"

[dev-dependencies.etherparse]
path = "."
version = "0.4.0"
features = ["proptest"]

[badges]
travis-ci = { repository = "JulianSchmid/etherparse", branch = "master" }
codecov = { repository = "JulianSchmid/etherparse", branch = "master", service = "github" }
